# Generated by Django 2.2.6 on 2019-12-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mytable_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=200)),
                ('email', models.FileField(upload_to='static/IMAGES')),
            ],
        ),
        migrations.DeleteModel(
            name='sample',
        ),
    ]
