# Generated by Django 2.2.6 on 2019-12-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0002_auto_20191215_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytable_test',
            old_name='email',
            new_name='file',
        ),
    ]
